export const KeyStatus = Object.freeze({
  ACTIVE: "active",
  PRISTINE: "pristine",
  RESET: "reset",
  WORKING: "working",
});

export const KeyCodes = Object.freeze({
  Escape: "Escape",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  //
  Backquote: "Backquote",
  Digit1: "Digit1",
  Digit2: "Digit2",
  Digit3: "Digit3",
  Digit4: "Digit4",
  Digit5: "Digit5",
  Digit6: "Digit6",
  Digit7: "Digit7",
  Digit8: "Digit8",
  Digit9: "Digit9",
  Digit0: "Digit0",
  Minus: "Minus",
  Equal: "Equal",
  Backspace: "Backspace",
  //
  Tab: "Tab",
  KeyQ: "KeyQ",
  KeyW: "KeyW",
  KeyE: "KeyE",
  KeyR: "KeyR",
  KeyT: "KeyT",
  KeyY: "KeyY",
  KeyU: "KeyU",
  KeyI: "KeyI",
  KeyO: "KeyO",
  KeyP: "KeyP",
  BracketLeft: "BracketLeft",
  BracketRight: "BracketRight",
  Backslash: "Backslash",
  //
  CapsLock: "CapsLock",
  KeyA: "KeyA",
  KeyS: "KeyS",
  KeyD: "KeyD",
  KeyF: "KeyF",
  KeyG: "KeyG",
  KeyH: "KeyH",
  KeyJ: "KeyJ",
  KeyK: "KeyK",
  KeyL: "KeyL",
  Semicolon: "Semicolon",
  Quote: "Quote",
  Enter: "Enter",
  //
  ShiftLeft: "ShiftLeft",
  KeyZ: "KeyZ",
  KeyX: "KeyX",
  KeyC: "KeyC",
  KeyV: "KeyV",
  KeyB: "KeyB",
  KeyN: "KeyN",
  KeyM: "KeyM",
  Comma: "Comma",
  Period: "Period",
  Slash: "Slash",
  ShiftRight: "ShiftRight",
  //
  ControlLeft: "ControlLeft",
  MetaLeft: "MetaLeft",
  AltLeft: "AltLeft",
  Space: "Space",
  MetaRight: "MetaRight",
  AltRight: "AltRight",
  ControlRight: "ControlRight",
  // ISO keys
  // TODO
  // Other
  Fn: "Fn", // actually inaccessible from the browser
  PrintScreen: "PrintScreen",
  ScrollLock: "ScrollLock",
  Pause: "Pause",
  Insert: "Insert",
  Home: "Home",
  PageUp: "PageUp",
  Delete: "Delete",
  End: "End",
  PageDown: "PageDown",
  ArrowUp: "ArrowUp",
  ArrowLeft: "ArrowLeft",
  ArrowRight: "ArrowRight",
  ArrowDown: "ArrowDown",
  NumLock: "NumLock",
  NumpadDivide: "NumpadDivide",
  NumpadMultiply: "NumpadMultiply",
  NumpadSubtract: "NumpadSubtract",
  Numpad7: "Numpad7",
  Numpad8: "Numpad8",
  Numpad9: "Numpad9",
  NumpadAdd: "NumpadAdd",
  Numpad4: "Numpad4",
  Numpad5: "Numpad5",
  Numpad6: "Numpad6",
  Numpad1: "Numpad1",
  Numpad2: "Numpad2",
  Numpad3: "Numpad3",
  NumpadEnter: "NumpadEnter",
  Numpad0: "Numpad0",
  NumpadDecimal: "NumpadDecimal",
});
