export const KeyStatus = Object.freeze({
  ACTIVE: "active",
  PRISTINE: "pristine",
  RESET: "reset",
  WORKING: "working",
});

export const KeyCodes = Object.freeze({
  Backquote: "Backquote",
  Digit1: "Digit1",
  Digit2: "Digit2",
  Digit3: "Digit3",
  Digit4: "Digit4",
  Digit5: "Digit5",
  Digit6: "Digit6",
  Digit7: "Digit7",
  Digit8: "Digit8",
  Digit9: "Digit9",
  Digit0: "Digit0",
  Minus: "Minus",
  Equal: "Equal",
  Backspace: "Backspace",
  //
  Tab: "Tab",
  KeyQ: "KeyQ",
  KeyW: "KeyW",
  KeyE: "KeyE",
  KeyR: "KeyR",
  KeyT: "KeyT",
  KeyY: "KeyY",
  KeyU: "KeyU",
  KeyI: "KeyI",
  KeyO: "KeyO",
  KeyP: "KeyP",
  BracketLeft: "BracketLeft",
  BracketRight: "BracketRight",
  Backslash: "Backslash",
  //
  CapsLock: "CapsLock",
  KeyA: "KeyA",
  KeyS: "KeyS",
  KeyD: "KeyD",
  KeyF: "KeyF",
  KeyG: "KeyG",
  KeyH: "KeyH",
  KeyJ: "KeyJ",
  KeyK: "KeyK",
  KeyL: "KeyL",
  Semicolon: "Semicolon",
  Quote: "Quote",
  Enter: "Enter",
  //
  ShiftLeft: "ShiftLeft",
  KeyZ: "KeyZ",
  KeyX: "KeyX",
  KeyC: "KeyC",
  KeyV: "KeyV",
  KeyB: "KeyB",
  KeyN: "KeyN",
  KeyM: "KeyM",
  Comma: "Comma",
  Period: "Period",
  Slash: "Slash",
  ShiftRight: "ShiftRight",
  //
  ControlLeft: "ControlLeft",
  MetaLeft: "MetaLeft",
  AltLeft: "AltLeft",
  Space: "Space",
  MetaRight: "MetaRight",
  AltRight: "AltRight",
  ControlRight: "ControlRight",
});
