import { KeyCodes } from "./constants";

export const Layouts = {
  ANSI: [
    [
      { keyCode: KeyCodes.Backquote, size: "1U", label: "^" },
      { keyCode: KeyCodes.Digit1, size: "1U", label: "1" },
      { keyCode: KeyCodes.Digit2, size: "1U", label: "2" },
      { keyCode: KeyCodes.Digit3, size: "1U", label: "3" },
      { keyCode: KeyCodes.Digit4, size: "1U", label: "4" },
      { keyCode: KeyCodes.Digit5, size: "1U", label: "5" },
      { keyCode: KeyCodes.Digit6, size: "1U", label: "6" },
      { keyCode: KeyCodes.Digit7, size: "1U", label: "7" },
      { keyCode: KeyCodes.Digit8, size: "1U", label: "8" },
      { keyCode: KeyCodes.Digit9, size: "1U", label: "9" },
      { keyCode: KeyCodes.Digit0, size: "1U", label: "0" },
      { keyCode: KeyCodes.Minus, size: "1U", label: "-" },
      { keyCode: KeyCodes.Equal, size: "1U", label: "=" },
      { keyCode: KeyCodes.Backspace, size: "1U", label: "←" },
    ],
    [
      { keyCode: KeyCodes.Tab, size: "1U", label: "↹" },
      { keyCode: KeyCodes.KeyQ, size: "1U", label: "Q" },
      { keyCode: KeyCodes.KeyW, size: "1U", label: "W" },
      { keyCode: KeyCodes.KeyE, size: "1U", label: "E" },
      { keyCode: KeyCodes.KeyR, size: "1U", label: "R" },
      { keyCode: KeyCodes.KeyT, size: "1U", label: "T" },
      { keyCode: KeyCodes.KeyY, size: "1U", label: "Y" },
      { keyCode: KeyCodes.KeyU, size: "1U", label: "U" },
      { keyCode: KeyCodes.KeyI, size: "1U", label: "I" },
      { keyCode: KeyCodes.KeyO, size: "1U", label: "O" },
      { keyCode: KeyCodes.KeyP, size: "1U", label: "P" },
      { keyCode: KeyCodes.BracketLeft, size: "1U", label: "[" },
      { keyCode: KeyCodes.BracketRight, size: "1U", label: "]" },
      { keyCode: KeyCodes.Backslash, size: "1U", label: "\\" },
    ],
    [
      { keyCode: KeyCodes.CapsLock, size: "1U", label: "⇪" },
      { keyCode: KeyCodes.KeyA, size: "1U", label: "A" },
      { keyCode: KeyCodes.KeyS, size: "1U", label: "S" },
      { keyCode: KeyCodes.KeyD, size: "1U", label: "D" },
      { keyCode: KeyCodes.KeyF, size: "1U", label: "F" },
      { keyCode: KeyCodes.KeyG, size: "1U", label: "G" },
      { keyCode: KeyCodes.KeyH, size: "1U", label: "H" },
      { keyCode: KeyCodes.KeyJ, size: "1U", label: "J" },
      { keyCode: KeyCodes.KeyK, size: "1U", label: "K" },
      { keyCode: KeyCodes.KeyL, size: "1U", label: "L" },
      { keyCode: KeyCodes.Semicolon, size: "1U", label: ";" },
      { keyCode: KeyCodes.Quote, size: "1U", label: '"' },
      { keyCode: KeyCodes.Enter, size: "1U", label: "↵" },
    ],
    [
      { keyCode: KeyCodes.ShiftLeft, size: "1U", label: "⇧" },
      { keyCode: KeyCodes.KeyZ, size: "1U", label: "Z" },
      { keyCode: KeyCodes.KeyX, size: "1U", label: "X" },
      { keyCode: KeyCodes.KeyC, size: "1U", label: "C" },
      { keyCode: KeyCodes.KeyV, size: "1U", label: "V" },
      { keyCode: KeyCodes.KeyB, size: "1U", label: "B" },
      { keyCode: KeyCodes.KeyN, size: "1U", label: "N" },
      { keyCode: KeyCodes.KeyM, size: "1U", label: "M" },
      { keyCode: KeyCodes.Comma, size: "1U", label: "," },
      { keyCode: KeyCodes.Period, size: "1U", label: "." },
      { keyCode: KeyCodes.Slash, size: "1U", label: "/" },
      { keyCode: KeyCodes.ShiftRight, size: "1U", label: "⇧" },
    ],
    [
      { keyCode: KeyCodes.ControlLeft, size: "1U", label: "Ctrl" },
      { keyCode: KeyCodes.MetaLeft, size: "1U", label: "Super" },
      { keyCode: KeyCodes.AltLeft, size: "1U", label: "Alt" },
      { keyCode: KeyCodes.Space, size: "1U", label: "Space" },
      { keyCode: KeyCodes.MetaRight, size: "1U", label: "Super" },
      { keyCode: KeyCodes.AltRight, size: "1U", label: "Alt" },
      { keyCode: KeyCodes.ControlRight, size: "1U", label: "Ctrls" },
    ],
  ],
};
