import { KeyCodes } from "./constants";

export const Layouts = {
  ANSI: [
    [
      { type: "Key", keyCode: KeyCodes.Escape, size: "1U", label: "Escape" },
      { type: "Spacing", size: "1U" },
      { type: "Key", keyCode: KeyCodes.F1, size: "1U", label: "F1" },
      { type: "Key", keyCode: KeyCodes.F2, size: "1U", label: "F2" },
      { type: "Key", keyCode: KeyCodes.F3, size: "1U", label: "F3" },
      { type: "Key", keyCode: KeyCodes.F4, size: "1U", label: "F4" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.F5, size: "1U", label: "F5" },
      { type: "Key", keyCode: KeyCodes.F6, size: "1U", label: "F6" },
      { type: "Key", keyCode: KeyCodes.F7, size: "1U", label: "F7" },
      { type: "Key", keyCode: KeyCodes.F8, size: "1U", label: "F8" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.F9, size: "1U", label: "F9" },
      { type: "Key", keyCode: KeyCodes.F10, size: "1U", label: "F10" },
      { type: "Key", keyCode: KeyCodes.F11, size: "1U", label: "F11" },
      { type: "Key", keyCode: KeyCodes.F12, size: "1U", label: "F12" },
      { type: "Spacing", size: "0.5U" },
      {
        type: "Key",
        keyCode: KeyCodes.PrintScreen,
        size: "1U",
        label: "Prt Scr",
      },
      {
        type: "Key",
        keyCode: KeyCodes.ScrollLock,
        size: "1U",
        label: "Scroll/Lock",
      },
      { type: "Key", keyCode: KeyCodes.Pause, size: "1U", label: "Pause" },
    ],
    [{ type: "Spacing", size: "0.5U" }],
    [
      { type: "Key", keyCode: KeyCodes.Backquote, size: "1U", label: "^" },
      { type: "Key", keyCode: KeyCodes.Digit1, size: "1U", label: "1" },
      { type: "Key", keyCode: KeyCodes.Digit2, size: "1U", label: "2" },
      { type: "Key", keyCode: KeyCodes.Digit3, size: "1U", label: "3" },
      { type: "Key", keyCode: KeyCodes.Digit4, size: "1U", label: "4" },
      { type: "Key", keyCode: KeyCodes.Digit5, size: "1U", label: "5" },
      { type: "Key", keyCode: KeyCodes.Digit6, size: "1U", label: "6" },
      { type: "Key", keyCode: KeyCodes.Digit7, size: "1U", label: "7" },
      { type: "Key", keyCode: KeyCodes.Digit8, size: "1U", label: "8" },
      { type: "Key", keyCode: KeyCodes.Digit9, size: "1U", label: "9" },
      { type: "Key", keyCode: KeyCodes.Digit0, size: "1U", label: "0" },
      { type: "Key", keyCode: KeyCodes.Minus, size: "1U", label: "-" },
      { type: "Key", keyCode: KeyCodes.Equal, size: "1U", label: "=" },
      { type: "Key", keyCode: KeyCodes.Backspace, size: "2U", label: "←" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.Insert, size: "1U", label: "Insert" },
      { type: "Key", keyCode: KeyCodes.Home, size: "1U", label: "Home" },
      { type: "Key", keyCode: KeyCodes.PageUp, size: "1U", label: "PgUp" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.NumLock, size: "1U", label: "NmLock" },
      { type: "Key", keyCode: KeyCodes.NumpadDivide, size: "1U", label: "/" },
      { type: "Key", keyCode: KeyCodes.NumpadMultiply, size: "1U", label: "*" },
      { type: "Key", keyCode: KeyCodes.NumpadSubtract, size: "1U", label: "-" },
    ],
    [
      { type: "Key", keyCode: KeyCodes.Tab, size: "1.5U", label: "↹" },
      { type: "Key", keyCode: KeyCodes.KeyQ, size: "1U", label: "Q" },
      { type: "Key", keyCode: KeyCodes.KeyW, size: "1U", label: "W" },
      { type: "Key", keyCode: KeyCodes.KeyE, size: "1U", label: "E" },
      { type: "Key", keyCode: KeyCodes.KeyR, size: "1U", label: "R" },
      { type: "Key", keyCode: KeyCodes.KeyT, size: "1U", label: "T" },
      { type: "Key", keyCode: KeyCodes.KeyY, size: "1U", label: "Y" },
      { type: "Key", keyCode: KeyCodes.KeyU, size: "1U", label: "U" },
      { type: "Key", keyCode: KeyCodes.KeyI, size: "1U", label: "I" },
      { type: "Key", keyCode: KeyCodes.KeyO, size: "1U", label: "O" },
      { type: "Key", keyCode: KeyCodes.KeyP, size: "1U", label: "P" },
      { type: "Key", keyCode: KeyCodes.BracketLeft, size: "1U", label: "[" },
      { type: "Key", keyCode: KeyCodes.BracketRight, size: "1U", label: "]" },
      { type: "Key", keyCode: KeyCodes.Backslash, size: "1.5U", label: "\\" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.Delete, size: "1U", label: "Delete" },
      { type: "Key", keyCode: KeyCodes.End, size: "1U", label: "End" },
      { type: "Key", keyCode: KeyCodes.PageDown, size: "1U", label: "PgDown" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.Numpad7, size: "1U", label: "7" },
      { type: "Key", keyCode: KeyCodes.Numpad8, size: "1U", label: "8" },
      { type: "Key", keyCode: KeyCodes.Numpad9, size: "1U", label: "9" },
      { type: "Key", keyCode: KeyCodes.NumpadAdd, size: "1U", label: "+" },
    ],
    [
      { type: "Key", keyCode: KeyCodes.CapsLock, size: "1.75U", label: "⇪" },
      { type: "Key", keyCode: KeyCodes.KeyA, size: "1U", label: "A" },
      { type: "Key", keyCode: KeyCodes.KeyS, size: "1U", label: "S" },
      { type: "Key", keyCode: KeyCodes.KeyD, size: "1U", label: "D" },
      { type: "Key", keyCode: KeyCodes.KeyF, size: "1U", label: "F" },
      { type: "Key", keyCode: KeyCodes.KeyG, size: "1U", label: "G" },
      { type: "Key", keyCode: KeyCodes.KeyH, size: "1U", label: "H" },
      { type: "Key", keyCode: KeyCodes.KeyJ, size: "1U", label: "J" },
      { type: "Key", keyCode: KeyCodes.KeyK, size: "1U", label: "K" },
      { type: "Key", keyCode: KeyCodes.KeyL, size: "1U", label: "L" },
      { type: "Key", keyCode: KeyCodes.Semicolon, size: "1U", label: ";" },
      { type: "Key", keyCode: KeyCodes.Quote, size: "1U", label: '"' },
      { type: "Key", keyCode: KeyCodes.Enter, size: "2.25U", label: "↵" },
      { type: "Spacing", size: "4U" },
      { type: "Key", keyCode: KeyCodes.Numpad4, size: "1U", label: "4" },
      { type: "Key", keyCode: KeyCodes.Numpad5, size: "1U", label: "5" },
      { type: "Key", keyCode: KeyCodes.Numpad6, size: "1U", label: "6" },
    ],
    [
      { type: "Key", keyCode: KeyCodes.ShiftLeft, size: "2.25U", label: "⇧" },
      { type: "Key", keyCode: KeyCodes.KeyZ, size: "1U", label: "Z" },
      { type: "Key", keyCode: KeyCodes.KeyX, size: "1U", label: "X" },
      { type: "Key", keyCode: KeyCodes.KeyC, size: "1U", label: "C" },
      { type: "Key", keyCode: KeyCodes.KeyV, size: "1U", label: "V" },
      { type: "Key", keyCode: KeyCodes.KeyB, size: "1U", label: "B" },
      { type: "Key", keyCode: KeyCodes.KeyN, size: "1U", label: "N" },
      { type: "Key", keyCode: KeyCodes.KeyM, size: "1U", label: "M" },
      { type: "Key", keyCode: KeyCodes.Comma, size: "1U", label: "," },
      { type: "Key", keyCode: KeyCodes.Period, size: "1U", label: "." },
      { type: "Key", keyCode: KeyCodes.Slash, size: "1U", label: "/" },
      { type: "Key", keyCode: KeyCodes.ShiftRight, size: "2.75U", label: "⇧" },
      { type: "Spacing", size: "1.5U" },
      { type: "Key", keyCode: KeyCodes.ArrowUp, size: "1U", label: "↑" },
      { type: "Spacing", size: "1.5U" },
      { type: "Key", keyCode: KeyCodes.Numpad1, size: "1U", label: "1" },
      { type: "Key", keyCode: KeyCodes.Numpad2, size: "1U", label: "2" },
      { type: "Key", keyCode: KeyCodes.Numpad3, size: "1U", label: "3" },
      { type: "Key", keyCode: KeyCodes.NumpadEnter, size: "1U", label: "↵" },
    ],
    [
      { type: "Key", keyCode: KeyCodes.Fn, size: "1.25U", label: "Fn" },
      {
        type: "Key",
        keyCode: KeyCodes.ControlLeft,
        size: "1.25U",
        label: "Ctrl",
      },
      {
        type: "Key",
        keyCode: KeyCodes.MetaLeft,
        size: "1.25U",
        label: "Super",
      },
      { type: "Key", keyCode: KeyCodes.AltLeft, size: "1.25U", label: "Alt" },
      { type: "Key", keyCode: KeyCodes.Space, size: "6.25U", label: "Space" },
      {
        type: "Key",
        keyCode: KeyCodes.MetaRight,
        size: "1.25U",
        label: "Super",
      },
      { type: "Key", keyCode: KeyCodes.AltRight, size: "1.25U", label: "Alt" },
      {
        type: "Key",
        keyCode: KeyCodes.ControlRight,
        size: "1.25U",
        label: "Ctrl",
      },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.ArrowLeft, size: "1U", label: "←" },
      { type: "Key", keyCode: KeyCodes.ArrowDown, size: "1U", label: "↓" },
      { type: "Key", keyCode: KeyCodes.ArrowRight, size: "1U", label: "→" },
      { type: "Spacing", size: "0.5U" },
      { type: "Key", keyCode: KeyCodes.Numpad0, size: "2U", label: "0" },
      { type: "Key", keyCode: KeyCodes.NumpadDecimal, size: "1U", label: "." },
    ],
  ],
};
